"use client";

import { useState, useTransition } from "react";
import { Plus, Repeat2, Trash2 } from "lucide-react";
import type { Category, RecurringTransaction, TransactionType, Frequency } from "@/lib/supabase/types";
import { createClient } from "@/lib/supabase/client";
import { euro, formatDate } from "@/lib/utils";
import { CategoryIcon } from "@/components/ui/category-icon";
import { Button, Card, Field, Select } from "@/components/ui/primitives";
import { PageHeading } from "@/components/ui/page-heading";
import { DateField } from "@/components/ui/date-field";

export function RecurringView({ recurring, categories, today }: { recurring: RecurringTransaction[]; categories: Category[]; today: string }) {
  const [rows, setRows] = useState(recurring); const [type, setType] = useState<TransactionType>("expense"); const [amount, setAmount] = useState(""); const [description, setDescription] = useState(""); const [categoryId, setCategoryId] = useState(""); const [frequency, setFrequency] = useState<Frequency>("monthly"); const [nextRun, setNextRun] = useState(today); const [error, setError] = useState(""); const [pending, startTransition] = useTransition();
  const save = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); const numericAmount = Number(amount.replace(",", ".")); if (!Number.isFinite(numericAmount) || numericAmount <= 0) { setError("Introduce un importe válido mayor que cero."); return; } startTransition(async () => {
    const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) { setError("Inicia sesión para guardar un movimiento recurrente."); return; }
    const { data, error: saveError } = await supabase.from("recurring_transactions").insert({ user_id: user.id, type, amount: numericAmount, description: description.trim(), category_id: categoryId || null, frequency, next_run: nextRun, end_date: null, active: true }).select().single();
    if (saveError) { setError("No se pudo guardar. Comprueba que el esquema de Supabase está aplicado."); return; }
    setRows((current) => [...current, data]); setAmount(""); setDescription("");
  }); };
  const toggle = (row: RecurringTransaction) => startTransition(async () => { const { error: updateError } = await createClient().from("recurring_transactions").update({ active: !row.active }).eq("id", row.id); if (!updateError) setRows((current) => current.map((item) => item.id === row.id ? { ...item, active: !item.active } : item)); });
  const remove = (row: RecurringTransaction) => startTransition(async () => { const { error: deleteError } = await createClient().from("recurring_transactions").delete().eq("id", row.id); if (!deleteError) setRows((current) => current.filter((item) => item.id !== row.id)); });
  return <div className="motion-enter max-w-5xl"><PageHeading description="Programa cargos e ingresos que se repiten y consulta la próxima fecha." backHref="/settings"/><div className="grid gap-4 md:gap-6 xl:grid-cols-2">
    <form onSubmit={save} className="card h-fit space-y-4 p-5 md:p-6"><div><h2 className="m-0 text-base font-semibold">Añadir recurrente</h2><p className="muted mb-0 mt-1 text-sm">Se registrará automáticamente en la fecha indicada.</p></div>
      <div className="grid grid-cols-2 rounded-xl bg-[var(--soft-blue)] p-1">{(["expense", "income"] as const).map((item) => <button key={item} type="button" onClick={() => { setType(item); setCategoryId(""); }} className={`min-h-10 rounded-lg text-sm font-medium ${type === item ? "bg-[var(--surface)] shadow-sm" : "muted"}`}>{item === "expense" ? "Gasto" : "Ingreso"}</button>)}</div>
      <label className="field-label">Importe<Field required inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="0,00 €" /></label>
      <label className="field-label">Descripción<Field required value={description} onChange={(event) => setDescription(event.target.value)} maxLength={160} placeholder="Alquiler, suscripción…" /></label>
      <label className="field-label">Categoría<Select className="native-select" value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">Sin categoría</option>{categories.filter((category) => category.type === type).map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</Select></label>
       <div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><label className="field-label">Frecuencia<Select className="native-select" value={frequency} onChange={(event) => setFrequency(event.target.value as Frequency)}><option value="weekly">Semanal</option><option value="monthly">Mensual</option><option value="yearly">Anual</option></Select></label><label className="field-label">Próxima fecha<DateField required value={nextRun} onChange={setNextRun} /></label></div>
      {error && <p className="m-0 text-sm text-[var(--expense)]" role="alert">{error}</p>}<Button disabled={pending} className="w-full"><Plus size={16}/>{pending ? "Guardando…" : "Guardar recurrente"}</Button>
    </form>
    <section className="motion-list space-y-3">{rows.length ? rows.map((row) => { const category = categories.find((item) => item.id === row.category_id); return <article key={row.id} className="card grid grid-cols-[40px_minmax(0,1fr)_auto] items-center gap-3 p-4"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[var(--soft-blue)]"><CategoryIcon name={category?.icon} size={18}/></span><div className="min-w-0"><strong className="block truncate text-sm">{row.description || category?.name || "Movimiento"}</strong><span className="muted mt-1 block text-xs">{category?.name || "Sin categoría"} · {row.frequency === "weekly" ? "Cada semana" : row.frequency === "monthly" ? "Cada mes" : "Cada año"}</span><span className="muted mt-1 block text-xs">Próximo: {formatDate(row.next_run)}</span></div><span className={`amount whitespace-nowrap text-sm font-semibold ${row.type === "income" ? "text-[var(--income)]" : ""}`}>{row.type === "income" ? "+" : "−"}{euro(row.amount)}</span><button onClick={() => toggle(row)} aria-label={row.active ? "Pausar movimiento" : "Reanudar movimiento"} className={`col-start-2 min-h-11 justify-self-start rounded-xl px-3 text-xs font-semibold sm:col-start-auto ${row.active ? "bg-[color-mix(in_srgb,var(--income)_14%,transparent)] text-[var(--income)]" : "bg-[var(--soft-blue)] text-[var(--muted)]"}`}>{row.active ? "Activo" : "Pausado"}</button><button onClick={() => remove(row)} aria-label="Eliminar recurrente" className="icon-button col-start-3 row-start-2 text-[var(--muted)] hover:bg-[var(--danger-soft)] hover:text-[var(--expense)] sm:row-start-auto"><Trash2 size={16}/></button></article>; }) : <Card className="flex min-h-48 flex-col items-center justify-center text-center"><Repeat2 className="muted mb-3" size={22}/><strong className="text-sm">Aún no tienes movimientos recurrentes</strong><p className="muted mb-0 mt-1 text-sm">Añade un alquiler o una suscripción y aparecerá aquí.</p></Card>}</section>
  </div></div>;
}
