import {
  Baby, Bike, BookOpen, BriefcaseBusiness, Bus, CarFront, Circle, CircleDollarSign,
  CircleEllipsis, CirclePlus, Clapperboard, Coffee, Dumbbell, Fuel, Gamepad2,
  Gift, Heart, HeartPulse, House, Landmark, Leaf, Lightbulb, Music, PawPrint,
  Pill, Plane, PiggyBank, ReceiptText, Repeat2, Shirt, ShoppingBag,
  ShoppingBasket, Smartphone, Sparkles, Stethoscope, TrainFront, Utensils,
  Wallet, Wifi, Wrench,
} from "lucide-react";

const icons = {
  house: House,
  "shopping-basket": ShoppingBasket,
  "train-front": TrainFront,
  sparkles: Sparkles,
  "heart-pulse": HeartPulse,
  "shopping-bag": ShoppingBag,
  "circle-ellipsis": CircleEllipsis,
  "briefcase-business": BriefcaseBusiness,
  "circle-plus": CirclePlus,
  circle: Circle,
  wallet: Wallet,
  utensils: Utensils,
  coffee: Coffee,
  car: CarFront,
  fuel: Fuel,
  bus: Bus,
  plane: Plane,
  gift: Gift,
  pets: PawPrint,
  clothing: Shirt,
  phone: Smartphone,
  internet: Wifi,
  electricity: Lightbulb,
  sport: Dumbbell,
  cinema: Clapperboard,
  music: Music,
  games: Gamepad2,
  education: BookOpen,
  medical: Stethoscope,
  pharmacy: Pill,
  children: Baby,
  bank: Landmark,
  savings: PiggyBank,
  receipts: ReceiptText,
  subscriptions: Repeat2,
  repairs: Wrench,
  nature: Leaf,
  cycling: Bike,
  work: BriefcaseBusiness,
  donations: Heart,
  money: CircleDollarSign,
  vivienda: House,
  alimentación: ShoppingBasket,
  transporte: TrainFront,
  ocio: Coffee,
} as const;

export function CategoryIcon({ name, size = 18 }: { name?: string | null; size?: number }) {
  const key = (name || "circle").toLocaleLowerCase("es-ES") as keyof typeof icons;
  const Icon = icons[key] || Circle;
  return <Icon size={size} aria-hidden="true" />;
}

export const categoryIconOptions = [
  { value: "house", label: "Vivienda" },
  { value: "shopping-basket", label: "Alimentación" },
  { value: "train-front", label: "Transporte" },
  { value: "sparkles", label: "Ocio" },
  { value: "heart-pulse", label: "Salud" },
  { value: "shopping-bag", label: "Compras" },
  { value: "circle-ellipsis", label: "Otros gastos" },
  { value: "briefcase-business", label: "Nómina" },
  { value: "circle-plus", label: "Otros ingresos" },
  { value: "wallet", label: "Ahorro" },
  { value: "utensils", label: "Restaurante" },
  { value: "coffee", label: "Café" },
  { value: "car", label: "Coche" },
  { value: "fuel", label: "Gasolina" },
  { value: "bus", label: "Autobús" },
  { value: "plane", label: "Avión y viajes" },
  { value: "gift", label: "Regalos" },
  { value: "pets", label: "Mascotas" },
  { value: "clothing", label: "Ropa" },
  { value: "phone", label: "Móvil" },
  { value: "internet", label: "Internet" },
  { value: "electricity", label: "Luz y suministros" },
  { value: "sport", label: "Deporte" },
  { value: "cinema", label: "Cine" },
  { value: "music", label: "Música" },
  { value: "games", label: "Juegos" },
  { value: "education", label: "Educación" },
  { value: "medical", label: "Médico" },
  { value: "pharmacy", label: "Farmacia" },
  { value: "children", label: "Niños" },
  { value: "bank", label: "Banco" },
  { value: "savings", label: "Hucha" },
  { value: "receipts", label: "Recibos" },
  { value: "subscriptions", label: "Suscripciones" },
  { value: "repairs", label: "Reparaciones" },
  { value: "nature", label: "Naturaleza" },
  { value: "cycling", label: "Bicicleta" },
  { value: "work", label: "Trabajo" },
  { value: "donations", label: "Donaciones" },
  { value: "money", label: "Dinero" },
];
